# Generated by Django 4.2.14 on 2025-01-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appsocialmedia', '0002_remove_comment_user_remove_post_user_comment_profil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Begenenler', to='Appsocialmedia.profil'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_save',
            field=models.ManyToManyField(blank=True, related_name='kaydedenler', to='Appsocialmedia.profil'),
        ),
    ]
