# Generated by Django 4.2.17 on 2025-01-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appsocialmedia", "0003_alter_post_likes_alter_post_post_save"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.ImageField(default=0, upload_to=""),
        ),
    ]
