# Generated by Django 4.2.17 on 2025-01-12 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appsocialmedia", "0004_post_comment_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="comment", new_name="comment1",
        ),
    ]
