# Generated by Django 4.2.17 on 2025-01-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appsocialmedia", "0005_rename_comment_comment_comment1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
    ]
