# Generated by Django 4.2.17 on 2025-01-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appsocialmedia", "0006_alter_post_comment_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="comment1", new_name="comment_text",
        ),
    ]
