# Generated by Django 4.2.17 on 2025-01-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appsocialmedia", "0007_rename_comment1_comment_comment_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=100)),
                ("receiver", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
